### ISSUE TITLE
Hello, I can't use it on my cell phone.

### ISSUE THREAD

**Issue by jeremy16601** [Inndy/vue-clipboard2#18]
Hello, I can't use it on my cell phone.

**Comment by someother1** [comment]
pls be more specifiy.. 
are you using an nokia 3310?
U see the problem? no description about anything - the error could also be anything..

which phone, which browser in which version?
Would also be nice to have an testcase (website with the error) to reconstruct the error, so that the maintainer does not have to spend much time into investigation of the error.

**Comment by Inndy** [comment]
I'm sorry, can't help with such description.
